### ISSUE TITLE
用自己数据集训练的pt转onnx后置信度降低

### ISSUE THREAD

**Issue by Nolan0206** [UNeedCryDear/yolov7-opencv-dnn-cpp#1]
跑官方80类的yolov7.pt转onnx的效果很好，但跑自己数据集训练的pt转onnx后，只修改了std::vector<std::string> className ，只有一类，然后检测效果下降了一半，pt的时候效果还是90多，转onnx后只有40多了。
请问是我还有没修改的位置，导致结果异常吗？

**Comment by UNeedCryDear** [comment]
1.看下你的检测框位置正确吗？还是说位置正确只有精度下降了？如果是单单精度下降的话，你可以试试将图片预处理改成yolo的预处理方式，我是为了速度直接贴到黑色背景的左上角的然后缩放，官方的处理是先缩放，然后填充114

**Comment by anlan-he** [comment]
您好，在VS2019中打开，main.cpp文件24行有Yolo test，显示Yolo未定义，请问这是怎么回事呢？
