### ISSUE TITLE
环境配置好后，出现如下报错在vs2019上，请问应该如何解决呢

### ISSUE THREAD

**Issue by baipengfeifei** [UNeedCryDear/yolov7-opencv-dnn-cpp#11]
0x00007FFCFE362A90 (opencv_world455.dll)处(位于 yolov7.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000028A24232000 时发生访问冲突。

**Comment by UNeedCryDear** [comment]
哪一行的报错要确定位置，目前我只能知道你这个报错是内存越界问题导致的，至于是哪里越界要确定下，你看下是不是图片路径不对导致的问题

**Comment by baipengfeifei** [comment]
> 哪一行的报错要确定位置，目前我只能知道你这个报错是内存越界问题导致的，至于是哪里越界要确定下，你看下是不是图片路径不对导致的问题
<img width="905" alt="1695108698880" src="https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/assets/99719143/df5e729e-e860-4444-85df-7c1124508fc7">
						minMaxLoc(scores, 0, &max_class_socre, 0, &classIdPoint);这行代码会报下边的错：0x00007FF896720570 (opencv_core455.dll)处(位于 yolov7.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000024460170000 时发生访问冲突。另外根据您的建议我查看了图片路径，绝对路径和相对路径都试过了，还是不行，请问应该如何解决

**Comment by UNeedCryDear** [comment]
如果你用的是自己的模型，请修改头文件中的类名参数，如果导出的onnx imgs参数非640，一样需要修改对应的参数

**Comment by baipengfeifei** [comment]
按照您的建议改好之后，图片的检测会有很奇怪的颜色快：
<img width="1091" alt="1695110469260" src="https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/assets/99719143/f11852a0-80a2-4348-ba72-e924abc3c37d">
这种情况是为什么呢，我在不使用yolov7相关代码的情况下使用opencv库来操作图片的时候没有出现这种情况

**Comment by UNeedCryDear** [comment]
https://netron.app/
用这个打开你的onnx文件，然后截图我看下模型的输出和output节点信息

**Comment by baipengfeifei** [comment]
> https://netron.app/ 用这个打开你的onnx文件，然后截图我看下模型的输出和output节点信息

感谢您的时间，这个问题已经解决啦，感谢！respect！
