### ISSUE TITLE
vector subscript out of range 报错

### ISSUE THREAD

**Issue by ZhangGanWei** [UNeedCryDear/yolov7-opencv-dnn-cpp#13]
![image](https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/assets/91108548/df025c19-36b4-4b0c-8bf3-e8260b7dbb39)

main执行到test.Detect时报这个错误

**Comment by UNeedCryDear** [comment]
越界了，你看下是不是类别数目没有修改

**Comment by ZhangGanWei** [comment]
感谢回复，考虑过是类别数目的问题，我是export.py（6.0以上版本）导出的yolov5s.onnx，检查了yolo.h里的类别似乎没有问题（未修改过）
![image](https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/assets/91108548/1d8001f1-327a-4120-90ef-89ca64917aad)

**Comment by ZhangGanWei** [comment]
@UNeedCryDear 感谢回复！刚刚查看了一下，yolo.cpp文件，发现通过宏定义切换版本时，只在main.cpp上切换了，而在yolo.cpp上仍然是yolov7，所以报了上述的错误。
