### ISSUE TITLE
关于推理时间的计算

### ISSUE THREAD

**Issue by ZhangGanWei** [UNeedCryDear/yolov7-opencv-dnn-cpp#14]
你的代码很棒，请问有没有尝试过计算过推理耗时？似乎在main.cpp中实现会比较麻烦

**Comment by UNeedCryDear** [comment]
如果你要计算推理耗时的话，在https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/blob/7547f390164d3f558893ecfb68cb608918e72020/yolo.cpp#L46 前后加上clock(),然后相减就是了。
如果你要计算从输入到获取最终结果的话，在https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/blob/7547f390164d3f558893ecfb68cb608918e72020/main.cpp#L46 计算Detect()的时间即可.

**Comment by ZhangGanWei** [comment]
感谢回复！尝试了一下输入到获取最终结果的，而release需要0.2~0.25s左右，结果合理吗（用过其他代码实现，结果是0.1~0.15s左右），这是我的计算方法：
![image](https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/assets/91108548/9a323339-73f7-48d8-9d83-ad99a6d0f95d)

另外如果使用自己训练的模型，代码中除了类别数目还有需要修改的地方吗，修改类别数目后，结果的框都集中在了右上角。

**Comment by UNeedCryDear** [comment]
200多ms也差不多是这个速度了，目前cpu的话好像是openvino速度会快一些，其他的基本上也就这样了。你说的100多ms是什么实现的，是否有涉及到显卡加速的问题

**Comment by ZhangGanWei** [comment]
100ms同是CPU实现，没有用到显卡，github连接：https://github.com/hpc203/yolov5-v6.1-opencv-onnxrun，里面也是用的opencv dnn模块实现检测。

请问如果使用自己训练的模型（仅更改了数据集，网络结构没变），代码中除了类别数目还有需要修改的地方吗？

**Comment by UNeedCryDear** [comment]
这个我没测试过，但是按理来说应该大差不差的，速度不会差距到五六十ms的，你可以多跑几次推理看下
使用自己的模型的话，看下你导出的onnx输入大小有没有变，如果没变的话只要改类别数据就ok，其他的像stride啥的默认的话就不需要动
还有一点要注意，就是看下你模型的netAnchors有没有变动，有些情况下开了自动anchors会由于数据集问题导致这个值变动，最终结果偏移不对
