### ISSUE TITLE
the pytorch version when export onnx model

### ISSUE THREAD

**Issue by ZhangGanWei** [UNeedCryDear/yolov7-opencv-dnn-cpp#15]
近期和小伙伴同步实现时发现一个问题，同样的6.0以上版本，小伙伴用的pytorch版本是1.8.0，我是1.12.1，再不做任何修改的情况的，导出onnx模型，可视化后发现onnx版本一个是v6 一个是v7。
这样的一个区别似乎在C++推理的时候对opencv的版本有所限制，在opencv4.5.4和4.5.5上测试了1.12.1pytorch版本导出了v6.0、v6.1、v6.2（6.2导出后和官网一致）下的onxx原模型，DNN的readNet都是失败的，换成opencv4.8.1后成功读取，请问作者在导出onnx模型时的pytorch版本为多少？出现这样的问题是因为低版本的opencvDNN不和onnx v7兼容吗？
![image](https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/assets/91108548/cd2873eb-4253-4518-84ca-f4d3bb726029)
![image](https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/assets/91108548/dc294c5a-80b7-4809-ad77-3ce7a249e8ab)

**Comment by UNeedCryDear** [comment]
我目前用的主要两个，一个是1.8.2LTS，一个是1.13.1
torch1.12这个版本问题比较多，还有一个是opset需要设置为12.
另外1.12导出onnx的时候，需要将torch.onnx.export（）里面的参数do_constant_folding=True,改为False看下

**Comment by ZhangGanWei** [comment]
感谢回复，确实是这个的问题，把No train改为了False后就可以了——另外1.12导出onnx的时候，需要将torch.onnx.export（）里面的参数do_constant_folding=True,改为False看下。
