### ISSUE TITLE
inference速度變慢了

### ISSUE THREAD

**Issue by boris0604** [UNeedCryDear/yolov7-opencv-dnn-cpp#2]
請問一下，轉成onnx後，inference的速度慢很多，請問參數哪裡還需要調整呢？
USE_CUDA 有設定為 true

**Comment by UNeedCryDear** [comment]
opencv是否编译了cuda？没有编译的话就是用的cpu推理，速度慢正常。如果编译了cuda速度还慢很多的话，请提供一下环境配置说明，主要是系统，显卡型号，cuda和cudnn版本，opencv版本号，或者可以给个复现的案例我查一下问题

**Comment by boris0604** [comment]
我想應該是編譯opencv_cuda版本用太新版的cudnn，我再調整一下，感謝回應

cv::dnn::cuda4dnn::checkVersions cuDNN reports version 8.0 which is not compatible with the version 8.5 with which OpenCV was built
cv::dnn::dnn4_v20211220::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type __NetInputLayer__

**Comment by boris0604** [comment]
修正後，還是比python慢。
在我的環境下，inference一張的平均時間
python: 15msec
c++(opencv+onnx): 30msec
不過說也奇了，放到jetson nano上就ok

**Comment by UNeedCryDear** [comment]
原因也挺多的，因为yolov7导出的onnx目前无法像yolov5那样合并三个输出口，这个也会慢一些些。另外就是cuda的话基本上前一两次可以去掉不计算时间的，cuda前几次会慢一些。另外就是绘图，存图时间不能计算，这个也会慢很多。另外还有一个就是，python下面是支持动态推理的，而opencv目前无法支持。举个例子来说，480x640的图片，python可以不经过padding，直接以480x640的大小推理，而opencv需要padding到640x640才行，这对于推理速度也会有影像的。另外一些就是更深入的调度上的一些问题，我也只是了解大概，具体我就不是很清楚了
