### ISSUE TITLE
OpenCV 4.4.0 + yolov7-tiny报错

### ISSUE THREAD

**Issue by tjuskyzhang** [UNeedCryDear/yolov7-opencv-dnn-cpp#21]
您好，用OpenCV 4.4.0推理yolov7-tiny报如下错误：
what(): 0penCV(4.4.0)_/home/***/opencv-4.4.0/modules/dnn/src/onnx/onnx importer.cpp:1410：error: (-2:Unspecified error) in function 'void cv::dnn::dnn4_v20200609::ONNXImporter::populateNet(cv::dnn::dnn4_v20200609::Net)'
>  (expected: 'shapes.depth() == CV_32S'), where
>     'shapes.depth()' is 5 (CV_32FC1)
> must be equal to
>     'CV_32S' is 4 (CV_32SC1)
项目限制死了4.4.0版本，想问一下能对yolov7做什么改动规避这个报错吗

**Comment by UNeedCryDear** [comment]
这个问题是你输入的图片数据格式不对，要求输入CV_32FC1，你当前输入是CV_32S，将其转成float看下

**Comment by tjuskyzhang** [comment]
OpenCV 4.4.0 onnx "Resize" 要求输入为int，nn.Upsample使用的nn.functional.interpolate的scale_factor参数（float），自己用nn.functional.interpolate的size参数（int）实现Upsample，重新训练、转换onnx模型就可以在OpenCV 4.4.0 上推理
