### ISSUE TITLE
如何進行batch inference?

### ISSUE THREAD

**Issue by pcchen-kid** [UNeedCryDear/yolov7-opencv-dnn-cpp#3]
您好。如果想要進行 batch inference 請問該怎麼修改呢？
我試著把 blobFromImage 改為 blobFromImages
forward 時，就會收到這個 exception
getLayerShapesRecursively OPENCV/DNN: [Permute]:(output): getMemoryShapes() throws exception. inputs=1 outputs=0/0 blobs=0

不知道您有什麼想法嗎？謝謝

**Comment by UNeedCryDear** [comment]
首先，批处理的话你需要在export的时候设置批处理大小，这个大小是固定死的，无法修改，也就是你导出的onnx只能以该batch size推理，因为目前opencv还不支持动态batch和动态HW的onnx。
其次，你需要将blobFromImage改成blobFromImages(),这个你已经知道了，关键是blobFromImages的第一个参数一定是batch size张图片的vector,后续一样。另外就是后处理，你需要加一个for循环，遍历每个batch size的输出。大概就是这样。
如果你真的有需要使用动态或者需要每次修改batch，H,W，比较建议的换成onnxruntime来推理，这样可以使用动态，不像opencv限制那么死。
