### ISSUE TITLE
yolov5 and yolov7  的差异

### ISSUE THREAD

**Issue by alicera** [UNeedCryDear/yolov7-opencv-dnn-cpp#4]
yolov5 and yolov7 
的差异在哪

decode and preprocess 应该没变?

**Comment by UNeedCryDear** [comment]
网络结构和一些模块不同我就不说了，这个你搜索一下很多大佬有说。我只说yolov5和yolov7在我推理代码中的不同。
首先就是yolov5合并三个输出口，以P5模型为例，输入1x3x640x640的tensor，
可以看到yolov5和yolov7在没有合并三个输出口的时候，都是P3层输出1x3x80x80x85,P4层输出1x3x40x40x85,P5层1x3x20x20x85，这三层的输出是一样的，也就是如果都不合并输出，的确是可以通用一套代码的（只有anchors不同，需要改下anchors）；
但是，关键就在于yolov5有合并三个输出，也就是有Detect层，将三个输出cat成一个，变成了1x25200x85;而yolov7加上Detect层之后，opencv无法读取和推理模型，所以yolov7在导出onnx的时候不加参数--grid，也就是没有Detect层，所以需要遍历
三个输出口，并且计算手动每个输出的anchors box，以替代Detect层的功能，这个就是在部署代码层面，yolov7和yolov5的最大不同。
如果yolov7在导出的时候可以使用--grid参数加上Detect层，并且opencv可以正确读取和推理，那么这两个也可以直接共用一套代码，连anchors都不需要修改，会自动计算。

**Comment by alicera** [comment]
谢谢

另外我试着转 yolov7-w6
'630', '633', '636', '639'  你知道是做什么用的? 维度怎么来?

```
Inputs:  ['images']
Outputs:  ['output', '667', '681', '695', '630', '633', '636', '639'] 
-------------------------------------------
input name images
input shape [1, 3, 1280, 1280]
input type tensor(float) 

output name: output
output shape: [1, 3, 160, 160, 85]
output type: tensor(float) 

output name: 667
output shape: [1, 3, 80, 80, 85]
output type: tensor(float) 

output name: 681
output shape: [1, 3, 40, 40, 85]
output type: tensor(float) 

output name: 695
output shape: [1, 3, 20, 20, 85]
output type: tensor(float) 

output name: 630
output shape: [1, 320, 160, 160]
output type: tensor(float) 

output name: 633
output shape: [1, 640, 80, 80]
output type: tensor(float) 

output name: 636
output shape: [1, 960, 40, 40]
output type: tensor(float) 

output name: 639
output shape: [1, 1280, 20, 20]
output type: tensor(float) 

```

**Comment by UNeedCryDear** [comment]
W6哪来那么多的输出？我就4个输出
![image](https://user-images.githubusercontent.com/52729998/198940676-1a7b326f-a5d2-497d-bca9-11affa1b566b.png)

**Comment by alicera** [comment]
我试着将 yolov7-w6.pt  reparameterization 后再转 onnx 就变4个输出了

**Comment by UNeedCryDear** [comment]
那我就不是很清楚了，看维度有点类似anchors-grid，但是我也不确定是不是
