### ISSUE TITLE
在gpu上的速度比cpu要慢的多

### ISSUE THREAD

**Issue by xusen-7** [UNeedCryDear/yolov7-opencv-dnn-cpp#5]
这里是我在原本的代码里加入时间计算
![1670554370540](https://user-images.githubusercontent.com/50946571/206613547-007df475-2d05-4bca-8d17-31be9c64407b.jpg)

gpu上运行的速度 #define USE_CUDA true
![a72f8112c7bd50b2e5e626b22392072](https://user-images.githubusercontent.com/50946571/206613600-aacb2b33-d164-4f3f-b16d-4e75a551eed0.png)
cpu上的速度 #define USE_CUDA false
![a36e12f1c37574e714204f6bf3db7ea](https://user-images.githubusercontent.com/50946571/206613610-0cf27495-ff03-4801-8f62-54c83d638eeb.png)

**Comment by UNeedCryDear** [comment]
有无详细的环境之类的？这种一般是环境的问题比较大，比如cuda是否正确安装，opencv是否编译过cuda？</br>
另外，一般来说GPU前一两次运行速度会比较慢，你是否有经过模型预热之类的操作？看下后面几次的速度。</br>
最后一种可能，就是torch>=1.12.x的时候，导出的时候需要修改的参数问题导致的计算速度慢。我手上暂时没有linux的系统，所以无法测试相关情况

**Comment by xusen-7** [comment]
感谢回复！环境如下 :
cuda : Cuda compilation tools, release 11.3, V11.3.109
opencv: 4.5.5 (编译过cuda)
torch: 1.10.0a0+3fd9dcf (用torch.__version__打印出来就是这个..)
系统: Ubuntu 20.04.2 LTS ， 3.10.0-1160.80.1.el7.x86_64
模型训练是在https://github.com/WongKinYiu/yolov7
导出命令是 python export.py --weights runs/train/cls2_/weights/best.pt --end2end --simplify --topk-all 50 --iou-thres 0.65 --img-size 640 640 --max-wh 640

有试过在gpu上连续推理多张图片，还是一样的情况。

**Comment by UNeedCryDear** [comment]
我看了下我这里还是好的。你显卡是啥，看下支不支持FP16，如果不支持的话显卡速度的确反而会更慢。具体你可以将这里的
https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/blob/f47bebea17ed8550bb65319e1eff04206db47445/yolo.cpp#L16
改成```DNN_TARGET_CUDA```看下。如果这个再不行的话，那只能你自己找找原因看下了。另外，你这个导出参数里面，有用到的就simplify 和img-size这两个，其他由于不加grid参数，都没有用到。

**Comment by xusen-7** [comment]
喔，那可能就是因为显卡了，我的是1060。

**Comment by xusen-7** [comment]
果然是这样，我改过来之后速度飙升，非常感谢！问题解决了。
