### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by threadprogrammer** [UNeedCryDear/yolov7-opencv-dnn-cpp#6]
Hello. I'm just adding yolov7.onnx and want to do an inference on test image; But it throws **Segmentation Fault** error.
opencv => 4.7
ubuntu 22.4
g++ 11.3
USE_CUDA is false

for example when i log the steps, there are some nan values.
the log: -nan,6.95044e-43,9.3887e-44,6.5861e-44,-nan
these 2 nan values are pdata[0] and pdata[4]( but sometimes pdata[1] or pdata[2] becomes nan )
the code (Yolo::Detect method):
`for (int stride = 0; stride < strideSize; stride++) {
	float* pdata = (float*)netOutputImg[stride].data;
`

**Comment by UNeedCryDear** [comment]
First ,yolov7 should set this flag false. https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/blob/7547f390164d3f558893ecfb68cb608918e72020/yolo.h#L6
Sec, change this to your class name if custom model. https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/blob/7547f390164d3f558893ecfb68cb608918e72020/yolo.h#L64
Third,make sure that the img size is equal to Yolo.netWidth and Yolo.neiHeight when you export onnx.
At the same time, use this page  open your onnx model(https://netron.app/) to check how many outputs.
If three, set  [YOLO_P6 ](https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/blob/7547f390164d3f558893ecfb68cb608918e72020/yolo.h#L10) false. Four,set it true.
![image](https://user-images.githubusercontent.com/52729998/209746157-872fc5a4-9fa9-4fdb-a4d7-45ac5568090b.png)

![image](https://user-images.githubusercontent.com/52729998/209746043-ef5090ba-d560-4f22-aba4-0fd00bc07537.png)

**Comment by UNeedCryDear** [comment]
If there are still problems after the above modifications, can you provide your  model?

**Comment by adib-hosseini** [comment]
This is my ONNX output in Netron:
name: classes
type: float32[1,25200,4]
name: boxes
type: float32[1,25200,80]

Its shape is neither 3 nor 4. It has only classes and boxes with the above shapes.

**Comment by adib-hosseini** [comment]
What is the purpose of YOLO_P6 actually?

**Comment by UNeedCryDear** [comment]
Please export onnx with code like:
```
python path/to/export.py --weights yolov7.pt --img [640,640]
```
P6 is the same as P3,P4,P5，but it stride is 64.
https://github.com/ultralytics/yolov5/issues/2835#issuecomment-822029301
Both yolov5 and v7 use the P5-model by default, but sometimes the P6 model is used to detect oversized objects,such as yolov5s6.pt and yolov7-d6.pt

**Comment by adib-hosseini** [comment]
Thanks.

Downgrading opencv to 4.6.0 fixed my issue in segmentation fault

**Comment by adib-hosseini** [comment]
How can I read the onnx model file or pt model file without using any library(link opencv dnn module,...)?
(I know this is not part of the issue. But its important for me to load load model file into network in an embedded platform)

**Comment by UNeedCryDear** [comment]
sorry, I don't know

**Comment by adib-hosseini** [comment]
Thanks
