### ISSUE TITLE
How to export to onnx

### ISSUE THREAD

**Issue by rmsalinas** [UNeedCryDear/yolov7-opencv-dnn-cpp#7]
Hi, I am trying to use the code but I get the following error

[ERROR:0@0.173] global onnx_importer.cpp:1051 handleNode DNN/ONNX: ERROR during processing node with 5 inputs and 1 outputs: [NonMaxSuppression]:(onnx_node!/end2end/NonMaxSuppression) from domain='ai.onnx'

To convert from the original model I used the command indicated in the original yovov7 repo:

python3 export.py --weights ../yolov7.pt --grid --end2end --simplify         --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 640 640 --max-wh 640

Can you please help me?
Thanks

**Comment by UNeedCryDear** [comment]
Remove flag ```--grid``` and ```--end2end```
```
python path/to/export.py --weights  path/to/yolov7.pt 
```

**Comment by rmsalinas** [comment]
Thanks for your reply and your work. It works perfectly. Have you had the chance to adapt to yolov8? 
Thanks

**Comment by UNeedCryDear** [comment]
It is the Chinese New Year recently, so it will not be completed soon. Yolov8(opencv and onnxruntime) will be completed as soon as possible after the Lantern Festival.

**Comment by rmsalinas** [comment]
Thats is going to be gorgeous! Thanks a lot

**Comment by UNeedCryDear** [comment]
@rmsalinas Yolov8 has been completed. You can get it here: https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp

**Comment by UNeedCryDear** [comment]
@rmsalinas Yolov8 has been completed. You can get it here: https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp
