### ISSUE TITLE
使用自己训练的模型运行出错

### ISSUE THREAD

**Issue by iPengXPro** [UNeedCryDear/yolov7-opencv-dnn-cpp#8]
![image](https://user-images.githubusercontent.com/102793417/217525841-a9477e26-f660-4d0e-92ca-cb16576db27d.png)
![image](https://user-images.githubusercontent.com/102793417/217525984-8aaa715b-c878-46d6-a0a9-2e4e69421d78.png)
![image](https://user-images.githubusercontent.com/102793417/217526178-c1cc1926-5a5a-45bf-a111-8fe1d8988c01.png)
您好！我使用自己训练的模型，导出后和官方的只有图片上的差别，运行不了。请问我应该如何修正呢？

**Comment by UNeedCryDear** [comment]
你只有9个类别，修改下https://github.com/UNeedCryDear/yolov7-opencv-dnn-cpp/blob/7547f390164d3f558893ecfb68cb608918e72020/yolo.h#L64

**Comment by iPengXPro** [comment]
![image](https://user-images.githubusercontent.com/102793417/217529570-c60b2eea-60a2-4944-a014-145ca107aa35.png)
类别修改后，又报了这个错误...

**Comment by iPengXPro** [comment]
感谢您！问题解决了，是类别的问题！我实际训练的是四个类，改成四个类就可以了，模型网络图中那个“9”是9个类别的意思吗？我实际训练四个类别为啥导出会是九个呢？好奇怪啊

**Comment by UNeedCryDear** [comment]
> 感谢您！问题解决了，是类别的问题！我实际训练的是四个类，改成四个类就可以了，模型网络图中那个“9”是9个类别的意思吗？我实际训练四个类别为啥导出会是九个呢？好奇怪啊

我脑子混了，是4个类别。长度为9=4个检测框数据+一个检测框置信度+4个类别置信度，所以只有4类

**Comment by iPengXPro** [comment]
感谢大佬指点迷津膜！
